version: '3.7'

services:

  api-gateway:
    image: node:18
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    ports:
      - 3003:3000
    command: sh -c 'yarn install && yarn start'
    restart: on-failure
    depends_on:
      - product-hub
      - stock-hub
  
  product-hub:
    image: node:18
    working_dir: /app
    ports:
      - 3004:3000
    volumes:
      - ./product-hub:/app
    restart: on-failure
    command: sh -c 'yarn install && yarn start'
    depends_on:
      - mysql
      - rabbitmq

  stock-hub:
    image: node:18
    working_dir: /app
    ports:
      - 3005:3000
    volumes:
      - ./stock-hub:/app
    restart: on-failure
    command: sh -c 'yarn install && yarn start'
    depends_on:
      - mysql
      - rabbitmq

  price-hub:
    image: node:18
    working_dir: /app
    ports:
      - 3006:3000
    volumes:
      - ./price-hub:/app
    restart: on-failure
    command: sh -c 'yarn install && yarn start'
    depends_on:
      - mysql
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root" 
      MYSQL_DATABASE: "ms"
      MYSQL_USER: "user" 
      MYSQL_PASSWORD: "user"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistir los datos de MySQL

volumes:
  rabbitmq_data:
  mysql_data: