version: '3.7'

services:

  api-gateway:
    image: node:18
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    ports:
      - 3003:3000
    command: sh -c 'yarn install && yarn start'
    restart: on-failure
    depends_on:
      - product-hub
      - stock-hub
  
  product-hub:
    image: node:18
    working_dir: /app
    ports:
      - 3004:3000
    volumes:
      - ./product-hub:/app
    restart: on-failure
    command: sh -c 'yarn install && yarn start'
    depends_on:
      - mysql
      - rabbitmq

  stock-hub:
    image: node:18
    working_dir: /app
    ports:
      - 3005:3000
    volumes:
      - ./stock-hub:/app
    restart: on-failure
    command: sh -c 'yarn install && yarn start'
    depends_on:
      - mysql
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"  # Puerto para la comunicación AMQP
      - "15672:15672"  # Puerto para el panel de control web de RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistir los datos de RabbitMQ

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"  # Cambia por una contraseña segura
      MYSQL_DATABASE: "ms"  # Cambia por el nombre de tu base de datos
      MYSQL_USER: "user"  # Cambia por el nombre de usuario de MySQL
      MYSQL_PASSWORD: "user"  # Cambia por una contraseña segura
    volumes:
      - mysql_data:/var/lib/mysql  # Persistir los datos de MySQL

volumes:
  rabbitmq_data:
  mysql_data: